// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"encoding/json"
)

type Article struct {
	ID      string
	Content json.RawMessage
	Title   string
}

type ArticleQueue struct {
	ID     int32
	Title  string
	Ondate sql.NullString
}

type Game struct {
	PlayerID string
	GameID   string
	GameData json.RawMessage
}
